// Generated by tools/build_planner_decor.mjs from tryon/js/catalog.js (2026-09-25). Do not edit.
export const DECOR_PRODUCTS = [
 {
  "id": "orbi-sphere-pendant",
  "name": "Alabaster Orbi Sphere Pendant",
  "kind": "pendant",
  "widthCm": 14,
  "heightCm": 14,
  "watts": 3,
  "lm": null,
  "ccts": [
   3000
  ],
  "finish": "Stone White",
  "handle": "archilight-alabaster-stone-orbi-sphere-pendant-140",
  "url": "https://wellforces.co.nz/products/archilight-alabaster-stone-orbi-sphere-pendant-140",
  "image": "assets/products/archilight-alabaster-stone-orbi-sphere-pendant-140.png",
  "variants": [
   {
    "sku": "ALA-94005-140A"
   }
  ]
 },
 {
  "id": "orbi-disc-pendant",
  "name": "Alabaster Orbi Disc Pendant",
  "kind": "pendant",
  "widthCm": 23,
  "heightCm": 12,
  "watts": 3,
  "lm": null,
  "ccts": [
   3000
  ],
  "finish": "Stone White",
  "handle": "archilight-alabaster-stone-orbi-disc-pendant",
  "url": "https://wellforces.co.nz/products/archilight-alabaster-stone-orbi-disc-pendant",
  "image": "assets/products/archilight-alabaster-stone-orbi-disc-pendant.png",
  "variants": [
   {
    "sku": "ALA-93090-230"
   }
  ]
 },
 {
  "id": "halo-pendant-340",
  "name": "Alabaster Halo Pendant 340",
  "kind": "pendant",
  "widthCm": 34,
  "heightCm": 6,
  "watts": 12,
  "lm": null,
  "ccts": [
   3000
  ],
  "finish": "Stone White",
  "handle": "archilight-alabaster-stone-halo-pendant-340",
  "url": "https://wellforces.co.nz/products/archilight-alabaster-stone-halo-pendant-340",
  "image": "assets/products/archilight-alabaster-stone-halo-pendant-340.png",
  "variants": [
   {
    "sku": "ALA-70066-340"
   }
  ]
 },
 {
  "id": "halo-pendant-790",
  "name": "Alabaster Halo Pendant 790",
  "kind": "pendant",
  "widthCm": 79,
  "heightCm": 6,
  "watts": 22,
  "lm": null,
  "ccts": [
   3000
  ],
  "finish": "Stone White",
  "handle": "archilight-alabaster-stone-halo-pendant-790",
  "url": "https://wellforces.co.nz/products/archilight-alabaster-stone-halo-pendant-790",
  "image": "assets/products/archilight-alabaster-stone-halo-pendant-790.png",
  "variants": [
   {
    "sku": "ALA-70066-790"
   }
  ]
 },
 {
  "id": "vertical-spindle-pendant",
  "name": "Alabaster Vertical Spindle Pendant",
  "kind": "pendant",
  "widthCm": 7,
  "heightCm": 40,
  "watts": 11,
  "lm": null,
  "ccts": [
   3000
  ],
  "finish": "Stone White",
  "handle": "archilight-alabaster-stone-vertical-spindle-pendant-400",
  "url": "https://wellforces.co.nz/products/archilight-alabaster-stone-vertical-spindle-pendant-400",
  "image": "assets/products/archilight-alabaster-stone-vertical-spindle-pendant-400.png",
  "variants": [
   {
    "sku": "ALA-94006-400-V"
   }
  ]
 },
 {
  "id": "horizontal-spindle-pendant",
  "name": "Alabaster Horizontal Spindle Pendant",
  "kind": "pendant",
  "widthCm": 117.5,
  "heightCm": 4.2,
  "watts": 45,
  "lm": null,
  "ccts": [
   3000
  ],
  "finish": "Stone White",
  "handle": "archilight-alabaster-stone-horizontal-spindle-pendant-1180",
  "url": "https://wellforces.co.nz/products/archilight-alabaster-stone-horizontal-spindle-pendant-1180",
  "image": "assets/products/archilight-alabaster-stone-horizontal-spindle-pendant-1180.png",
  "variants": [
   {
    "sku": "ALA-70202-1180-H"
   }
  ]
 },
 {
  "id": "shade-pendant",
  "name": "Alabaster Shade Pendant",
  "kind": "pendant",
  "widthCm": 12,
  "heightCm": 13.5,
  "watts": 3,
  "lm": null,
  "ccts": [
   3000
  ],
  "finish": "Stone White",
  "handle": "archilight-alabaster-stone-shade-pendant-120",
  "url": "https://wellforces.co.nz/products/archilight-alabaster-stone-shade-pendant-120",
  "image": "assets/products/archilight-alabaster-stone-shade-pendant-120.png",
  "variants": [
   {
    "sku": "ALA-940095-120"
   }
  ]
 },
 {
  "id": "orbi-semi-sphere-pendant",
  "name": "Alabaster Orbi Semi Sphere Pendant",
  "kind": "pendant",
  "widthCm": 12,
  "heightCm": 22,
  "watts": 3,
  "lm": null,
  "ccts": [
   3000
  ],
  "finish": "Stone White",
  "handle": "archilight-alabaster-stone-orbi-semi-sphere-pendant-120",
  "url": "https://wellforces.co.nz/products/archilight-alabaster-stone-orbi-semi-sphere-pendant-120",
  "image": "assets/products/archilight-alabaster-stone-orbi-semi-sphere-pendant-120.png",
  "variants": [
   {
    "sku": "ALA-94094-120A"
   }
  ]
 },
 {
  "id": "orbi-sphere-wall",
  "name": "Alabaster Orbi Sphere Wall Light",
  "kind": "wall",
  "widthCm": 14,
  "heightCm": 18,
  "watts": 3,
  "lm": null,
  "ccts": [
   3000
  ],
  "finish": "Stone White",
  "handle": "archilight-alabaster-stone-orbi-sphere-wall-light",
  "url": "https://wellforces.co.nz/products/archilight-alabaster-stone-orbi-sphere-wall-light",
  "image": "assets/products/archilight-alabaster-stone-orbi-sphere-wall-light.png",
  "variants": [
   {
    "sku": "ALA-71237"
   }
  ]
 },
 {
  "id": "halo-wall",
  "name": "Alabaster Halo Wall Light",
  "kind": "wall",
  "widthCm": 34,
  "heightCm": 7,
  "watts": 12,
  "lm": null,
  "ccts": [
   3000
  ],
  "finish": "Stone White",
  "handle": "archilight-alabaster-stone-halo-wall-light-340",
  "url": "https://wellforces.co.nz/products/archilight-alabaster-stone-halo-wall-light-340",
  "image": "assets/products/archilight-alabaster-stone-halo-wall-light-340.png",
  "variants": [
   {
    "sku": "ALA-71134-340"
   }
  ]
 },
 {
  "id": "spindle-wall",
  "name": "Alabaster Spindle Wall Light",
  "kind": "wall",
  "widthCm": 52,
  "heightCm": 8,
  "watts": 10,
  "lm": null,
  "ccts": [
   3000
  ],
  "finish": "Stone White",
  "handle": "archilight-alabaster-stone-horizontal-spindle-wall-light-520",
  "url": "https://wellforces.co.nz/products/archilight-alabaster-stone-horizontal-spindle-wall-light-520",
  "image": "assets/products/archilight-alabaster-stone-horizontal-spindle-wall-light-520.png",
  "variants": [
   {
    "sku": "ALA-71221-520-HC"
   }
  ]
 },
 {
  "id": "disk-wall",
  "name": "Alabaster Disk Wall Light",
  "kind": "wall",
  "widthCm": 25,
  "heightCm": 7.5,
  "watts": 7,
  "lm": null,
  "ccts": [
   3000
  ],
  "finish": "Stone White",
  "handle": "archilight-alabaster-stone-disk-wall-light-250",
  "url": "https://wellforces.co.nz/products/archilight-alabaster-stone-disk-wall-light-250",
  "image": "assets/products/archilight-alabaster-stone-disk-wall-light-250.png",
  "variants": [
   {
    "sku": "ALA-693039-250"
   }
  ]
 },
 {
  "id": "bok-wall",
  "name": "Bok Wall Light",
  "kind": "wall",
  "widthCm": 10,
  "heightCm": 10,
  "watts": 6,
  "lm": 358,
  "ccts": [
   3000
  ],
  "finish": "White",
  "handle": "archilight-decorative-bok-wall-light",
  "url": "https://wellforces.co.nz/products/archilight-decorative-bok-wall-light",
  "image": "assets/products/archilight-decorative-bok-wall-light.png",
  "variants": [
   {
    "sku": "ALD-339100004"
   }
  ]
 },
 {
  "id": "cyra-wall",
  "name": "Cyra Wall Light",
  "kind": "wall",
  "widthCm": 12,
  "heightCm": 7.3,
  "watts": 3,
  "lm": null,
  "ccts": [
   3000
  ],
  "finish": "White",
  "handle": "archilight-decorative-cyra-wall-light",
  "url": "https://wellforces.co.nz/products/archilight-decorative-cyra-wall-light",
  "image": "assets/products/archilight-decorative-cyra-wall-light.png",
  "variants": [
   {
    "sku": "ALD-236100004"
   }
  ]
 },
 {
  "id": "uriah-wall",
  "name": "Uriah Up/Down Wall Light",
  "kind": "wall",
  "widthCm": 11.3,
  "heightCm": 11,
  "watts": 14,
  "lm": 1160,
  "ccts": [
   3000
  ],
  "finish": "Black",
  "handle": "archilight-uriah-up-down-wall-light",
  "url": "https://wellforces.co.nz/products/archilight-uriah-up-down-wall-light",
  "image": "assets/products/archilight-uriah-up-down-wall-light.png",
  "variants": [
   {
    "sku": "TI-FW-0102-3K"
   }
  ]
 },
 {
  "id": "orbi-sphere-table",
  "name": "Alabaster Orbi Sphere Table Lamp",
  "kind": "table",
  "widthCm": 12,
  "heightCm": 12,
  "watts": 3,
  "lm": null,
  "ccts": [
   3000
  ],
  "finish": "Stone White",
  "handle": "archilight-alabaster-stone-orbi-sphere-table-lamp-120",
  "url": "https://wellforces.co.nz/products/archilight-alabaster-stone-orbi-sphere-table-lamp-120",
  "image": "assets/products/archilight-alabaster-stone-orbi-sphere-table-lamp-120.png",
  "variants": [
   {
    "sku": "ALA-70074-120"
   }
  ]
 },
 {
  "id": "orbi-oval-table",
  "name": "Alabaster Orbi Oval Table Lamp",
  "kind": "table",
  "widthCm": 17,
  "heightCm": 28,
  "watts": 5.5,
  "lm": null,
  "ccts": [
   3000
  ],
  "finish": "Stone White",
  "handle": "archilight-alabaster-stone-orbi-ovaltable-lamp",
  "url": "https://wellforces.co.nz/products/archilight-alabaster-stone-orbi-ovaltable-lamp",
  "image": "assets/products/archilight-alabaster-stone-orbi-ovaltable-lamp.png",
  "variants": [
   {
    "sku": "ALA-49754-170"
   }
  ]
 },
 {
  "id": "aksel-table",
  "name": "Aksel Table Lamp",
  "kind": "table",
  "widthCm": 11.5,
  "heightCm": 30.4,
  "watts": 2,
  "lm": null,
  "ccts": [
   2200,
   2700,
   3000
  ],
  "finish": "White",
  "handle": "archilight-decorative-aksel-table-lamp",
  "url": "https://wellforces.co.nz/products/archilight-decorative-aksel-table-lamp",
  "image": "assets/products/archilight-decorative-aksel-table-lamp.png",
  "variants": [
   {
    "sku": "ALD-332102404"
   }
  ]
 },
 {
  "id": "lexi-table",
  "name": "Lexi Table Light",
  "kind": "table",
  "widthCm": 19.3,
  "heightCm": 22.5,
  "watts": 2,
  "lm": 215,
  "ccts": [
   2200,
   2700,
   3000
  ],
  "finish": "Sage Green",
  "handle": "archilight-decorative-lexi-table-light",
  "url": "https://wellforces.co.nz/products/archilight-decorative-lexi-table-light",
  "image": "assets/products/archilight-decorative-lexi-table-light.png",
  "variants": [
   {
    "sku": "ALD-298100412"
   }
  ]
 },
 {
  "id": "tri-spear-floor",
  "name": "Tri-Spear Floor Light",
  "kind": "floor",
  "widthCm": 40.4,
  "heightCm": 201.2,
  "watts": 21,
  "lm": 1780,
  "ccts": [
   3000
  ],
  "finish": "Dark Grey",
  "handle": "archilight-decorative-floor-light-tri-spear",
  "url": "https://wellforces.co.nz/products/archilight-decorative-floor-light-tri-spear",
  "image": "assets/products/archilight-decorative-floor-light-tri-spear.png",
  "variants": [
   {
    "sku": "ALD-293500001"
   }
  ]
 }
];
